- name: Ansible instalacja kasy z ekranem dotykowym 2.2.15
  hosts: localhost
  user: root
  connection: local
  tasks:
    - include_vars: key_vault.yml

    - copy: content="{{  secret_key }}" dest="/tmp/klucz.apt"
    - copy: content="{{  brama_public_key }}" dest="/tmp/pub1"
    - copy: content="{{  ansible_public_key }}" dest="/tmp/pub2"

    - name: Dodanie usera ansiblenet
      user:
        name: ansiblenet
        comment: Ansible Netis User
        shell: /bin/bash
        uid: 1888

    - name: Ansiblenet do sudo
      lineinfile:
        path: /etc/sudoers
        regexp: '^ansiblenet'
        line: 'ansiblenet ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'        

    - name: Dodanie klucza publicznego do ansiblenet
      authorized_key:
        user: ansiblenet
        key: "{{ lookup('file', '/tmp/pub2') }}"
        validate_certs: no
        state: present

    - name: Dodanie klucza publicznego do root
      authorized_key:
        user: root
        key: "{{ lookup('file', '/tmp/pub1') }}"
        validate_certs: no
        state: present

    - name: Dodanie klucza do apta
      apt_key:
        data: "{{ lookup('file', '/tmp/klucz.apt') }}"
        state: present

    - name: Dodanie auth do repo
      blockinfile:
          path: /etc/apt/auth.conf.d/repo.conf
          block: | 
              machine repo.netis.pl
              login {{ repo_login }}
              password {{ repo_pass }}
          create: yes        

    - name: Wylaczenie aktualizcji apta na czas instalacji
      systemd:
        state: stopped
        name: "{{ item }}"
      loop:
        - apt-daily.service  
        - apt-daily.timer  
        - apt-daily-upgrade.timer  

      
    - apt_repository:
        repo: "{{ repo_netis }}"
        state: present
        
        
    - name: Zmiana hostname na kasaX    
      hostname:
        name: kasaX

    - name: Installacja paczek
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      loop:
        - zip
        - openvpn
        - curl
        - mariadb-server
        - openssh-server
        - build-essential
        - gpm
        - vim
        - joe
        - unzip
        - gdb
        - rsh-client
        - gawk
        - lynx
        - ifupdown
        - net-tools
        - openjdk-8-jre
        - fonts-roboto
        - fonts-roboto-fontface
        - fonts-roboto-hinted
        - fonts-roboto-unhinted
        - xorg
        - cups-bsd
        - curl
        - setserial
        - nmap
        - rsh-client
        - rdate
        - setserial

    - name: mysql plugin
      command: mysql -e "update  user set plugin = ''" mysql

    - name: restart mysql
      systemd:
        name: mysql
        state: restarted

    - unarchive:
        src: keys.tgz 
        dest: /etc/openvpn/

    - name: "Create link /etc/openvpn/client -> /etc/openvpn/keys/client"
      file:
       src: /etc/openvpn/keys.4/client.4.101.conf 
       dest: /etc/openvpn/client.4.101.conf
       state: link
  
    - name: Openvpn enable w systemd
      systemd:
        name: openvpn@client.4.101
        state: started
        enabled: yes

    - name: 'add 10. to /etc/hosts.allow'
      lineinfile:
        path: /etc/hosts.allow
        line: "ALL:10."  

    - name: "Create link /etc/openvpn/client -> /etc/openvpn/keys/client"
      file:
       src: /etc/openvpn/keys.4/client.4.101.conf 
       dest: /etc/openvpn/client.4.101.conf
       state: link

    - name: Change password for sklep
      shell: echo root:'{{ root_pass }}' | sudo chpasswd
      no_log: True

    - name: Allow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^#PermitRootLogin prohibit-password"
                  line="PermitRootLogin yes"
                  state=present

    - name: add webapp
      lineinfile:
        path: /etc/hosts
        line: "195.8.106.129 webapp.pep.pl"

    - name: Usuniecie paczek gnome, kde, lightdm
      apt:
        name: "{{ item }}"
        state: absent
        force: yes
        update_cache: yes
      loop:
        - gdm3
        - sddm
        - lightdm  
        - gdm  

    - name: Installacja paczek
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      loop:
        - kasnet-server-2.1.326=2.1.326r202007081056~bionic-1
        - xkasnet-client-2.2.15
        - xkasnet-client-trex-2.2.15
        - xinput-calibrator

    - name: Remove file .run-config
      file:
        path: /home/kasa/.run-config
        state: absent
          
    - name: chown /home/xkasnet
      file:
         path: /home/xkasnet/
         state: directory
         recurse: yes
         owner: kasa
         group: kasa

    - name: chmod /home/kasa/prerun.sh
      file:
         path: /home/kasa/prerun.sh
         state: file
         mode: a+x

    - name: Installacja paczek
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      loop:
        - xkasnet-client-autostart-2.2.15

    - name: Restart komputera
      command: reboot
